/***** DO NOT EDIT THIS FILE *****/
// APIDemos.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var APIDemos = {};

/*** script -- APIDemosTest ***/
APIDemos.APIDemosTest = function(app) {
	MT.Script.call(this, app, "APIDemosTest.mt");
};

APIDemos.APIDemosTest.prototype = new MT.Script;

APIDemos.APIDemosTest.prototype.call = function() {
	//run: APIDemosTest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.aPIDemosTest = function() {
	return new APIDemos.APIDemosTest(this);
};

